services:
  mongodb:
    image: mongo:7.0
    container_name: bam_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bam_bank
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: